"""Initial migration.

Revision ID: 484724c6feec
Revises: 
Create Date: 2024-06-16 19:55:23.785433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484724c6feec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=True),
    sa.Column('to_currency', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    # ### end Alembic commands ###
